/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tao_openglnativedemo_TriangleRender */

#ifndef _Included_com_tao_openglnativedemo_TriangleRender
#define _Included_com_tao_openglnativedemo_TriangleRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tao_openglnativedemo_TriangleRender
 * Method:    doSurfaceCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tao_openglnativedemo_TriangleRender_doSurfaceCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_tao_openglnativedemo_TriangleRender
 * Method:    doSurfaceChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tao_openglnativedemo_TriangleRender_doSurfaceChanged
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tao_openglnativedemo_TriangleRender
 * Method:    doDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tao_openglnativedemo_TriangleRender_doDrawFrame
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_tao_openglnativedemo_TriangleRender_readShaderFile
(JNIEnv *env, jobject self, jobject assetManager);

#ifdef __cplusplus
}
#endif
#endif
